server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~* ^/Build/.*\.wasm\.br$ {
        default_type application/wasm;
        add_header Content-Encoding br;
    }

    location ~* ^/Build/.*\.(data|symbols)\.br$ {
        default_type application/octet-stream;
        add_header Content-Encoding br;
    }

    location ~* ^/Build/.*\.(js|framework\.js)\.br$ {
        default_type application/javascript;
        add_header Content-Encoding br;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
